/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as GuestResetPasswordRouteImport } from './routes/_guest/reset-password'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestForgotPasswordRouteImport } from './routes/_guest/forgot-password'
import { Route as GuestAcceptInvitationRouteImport } from './routes/_guest/accept-invitation'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/_app/index'
import { Route as AuthenticatedAppNewClaimRouteImport } from './routes/_authenticated/_app/new-claim'
import { Route as AuthenticatedAppClaimsRouteImport } from './routes/_authenticated/_app/claims'
import { Route as AuthenticatedAppClaimsIndexRouteImport } from './routes/_authenticated/_app/claims.index'
import { Route as AuthenticatedAppClaimsClaimIdRouteImport } from './routes/_authenticated/_app/claims.$claimId'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestResetPasswordRoute = GuestResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => GuestRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const GuestForgotPasswordRoute = GuestForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRoute,
} as any)
const GuestAcceptInvitationRoute = GuestAcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => GuestRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNewClaimRoute =
  AuthenticatedAppNewClaimRouteImport.update({
    id: '/new-claim',
    path: '/new-claim',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClaimsRoute = AuthenticatedAppClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppClaimsIndexRoute =
  AuthenticatedAppClaimsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppClaimsRoute,
  } as any)
const AuthenticatedAppClaimsClaimIdRoute =
  AuthenticatedAppClaimsClaimIdRouteImport.update({
    id: '/$claimId',
    path: '/$claimId',
    getParentRoute: () => AuthenticatedAppClaimsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/brand': typeof BrandRoute
  '/test': typeof TestRoute
  '/accept-invitation': typeof GuestAcceptInvitationRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/claims': typeof AuthenticatedAppClaimsRouteWithChildren
  '/new-claim': typeof AuthenticatedAppNewClaimRoute
  '/': typeof AuthenticatedAppIndexRoute
  '/claims/$claimId': typeof AuthenticatedAppClaimsClaimIdRoute
  '/claims/': typeof AuthenticatedAppClaimsIndexRoute
}
export interface FileRoutesByTo {
  '/brand': typeof BrandRoute
  '/test': typeof TestRoute
  '/accept-invitation': typeof GuestAcceptInvitationRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/new-claim': typeof AuthenticatedAppNewClaimRoute
  '/': typeof AuthenticatedAppIndexRoute
  '/claims/$claimId': typeof AuthenticatedAppClaimsClaimIdRoute
  '/claims': typeof AuthenticatedAppClaimsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/brand': typeof BrandRoute
  '/test': typeof TestRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_guest/accept-invitation': typeof GuestAcceptInvitationRoute
  '/_guest/forgot-password': typeof GuestForgotPasswordRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/reset-password': typeof GuestResetPasswordRoute
  '/_authenticated/_app/claims': typeof AuthenticatedAppClaimsRouteWithChildren
  '/_authenticated/_app/new-claim': typeof AuthenticatedAppNewClaimRoute
  '/_authenticated/_app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/_app/claims/$claimId': typeof AuthenticatedAppClaimsClaimIdRoute
  '/_authenticated/_app/claims/': typeof AuthenticatedAppClaimsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/brand'
    | '/test'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/claims'
    | '/new-claim'
    | '/'
    | '/claims/$claimId'
    | '/claims/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/brand'
    | '/test'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/new-claim'
    | '/'
    | '/claims/$claimId'
    | '/claims'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_guest'
    | '/brand'
    | '/test'
    | '/_authenticated/_app'
    | '/_guest/accept-invitation'
    | '/_guest/forgot-password'
    | '/_guest/login'
    | '/_guest/reset-password'
    | '/_authenticated/_app/claims'
    | '/_authenticated/_app/new-claim'
    | '/_authenticated/_app/'
    | '/_authenticated/_app/claims/$claimId'
    | '/_authenticated/_app/claims/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  BrandRoute: typeof BrandRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/reset-password': {
      id: '/_guest/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof GuestResetPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/accept-invitation': {
      id: '/_guest/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof GuestAcceptInvitationRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app/': {
      id: '/_authenticated/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/new-claim': {
      id: '/_authenticated/_app/new-claim'
      path: '/new-claim'
      fullPath: '/new-claim'
      preLoaderRoute: typeof AuthenticatedAppNewClaimRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/claims': {
      id: '/_authenticated/_app/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof AuthenticatedAppClaimsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/claims/': {
      id: '/_authenticated/_app/claims/'
      path: '/'
      fullPath: '/claims/'
      preLoaderRoute: typeof AuthenticatedAppClaimsIndexRouteImport
      parentRoute: typeof AuthenticatedAppClaimsRoute
    }
    '/_authenticated/_app/claims/$claimId': {
      id: '/_authenticated/_app/claims/$claimId'
      path: '/$claimId'
      fullPath: '/claims/$claimId'
      preLoaderRoute: typeof AuthenticatedAppClaimsClaimIdRouteImport
      parentRoute: typeof AuthenticatedAppClaimsRoute
    }
  }
}

interface AuthenticatedAppClaimsRouteChildren {
  AuthenticatedAppClaimsClaimIdRoute: typeof AuthenticatedAppClaimsClaimIdRoute
  AuthenticatedAppClaimsIndexRoute: typeof AuthenticatedAppClaimsIndexRoute
}

const AuthenticatedAppClaimsRouteChildren: AuthenticatedAppClaimsRouteChildren =
  {
    AuthenticatedAppClaimsClaimIdRoute: AuthenticatedAppClaimsClaimIdRoute,
    AuthenticatedAppClaimsIndexRoute: AuthenticatedAppClaimsIndexRoute,
  }

const AuthenticatedAppClaimsRouteWithChildren =
  AuthenticatedAppClaimsRoute._addFileChildren(
    AuthenticatedAppClaimsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppClaimsRoute: typeof AuthenticatedAppClaimsRouteWithChildren
  AuthenticatedAppNewClaimRoute: typeof AuthenticatedAppNewClaimRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppClaimsRoute: AuthenticatedAppClaimsRouteWithChildren,
  AuthenticatedAppNewClaimRoute: AuthenticatedAppNewClaimRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GuestRouteChildren {
  GuestAcceptInvitationRoute: typeof GuestAcceptInvitationRoute
  GuestForgotPasswordRoute: typeof GuestForgotPasswordRoute
  GuestLoginRoute: typeof GuestLoginRoute
  GuestResetPasswordRoute: typeof GuestResetPasswordRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestAcceptInvitationRoute: GuestAcceptInvitationRoute,
  GuestForgotPasswordRoute: GuestForgotPasswordRoute,
  GuestLoginRoute: GuestLoginRoute,
  GuestResetPasswordRoute: GuestResetPasswordRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  BrandRoute: BrandRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
