/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as GuestResetPasswordRouteImport } from './routes/_guest/reset-password'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestForgotPasswordRouteImport } from './routes/_guest/forgot-password'
import { Route as GuestAcceptInvitationRouteImport } from './routes/_guest/accept-invitation'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/_app/index'
import { Route as AuthenticatedAppUsersRouteImport } from './routes/_authenticated/_app/users'
import { Route as AuthenticatedAppNewClaimRouteImport } from './routes/_authenticated/_app/new-claim'
import { Route as AuthenticatedAppInsurersRouteImport } from './routes/_authenticated/_app/insurers'
import { Route as AuthenticatedAppClientsRouteImport } from './routes/_authenticated/_app/clients'
import { Route as AuthenticatedAppClaimsRouteImport } from './routes/_authenticated/_app/claims'
import { Route as AuthenticatedAppUsersIndexRouteImport } from './routes/_authenticated/_app/users.index'
import { Route as AuthenticatedAppInsurersIndexRouteImport } from './routes/_authenticated/_app/insurers.index'
import { Route as AuthenticatedAppClientsIndexRouteImport } from './routes/_authenticated/_app/clients.index'
import { Route as AuthenticatedAppClaimsIndexRouteImport } from './routes/_authenticated/_app/claims.index'
import { Route as AuthenticatedAppInsurersInsurerIdRouteImport } from './routes/_authenticated/_app/insurers.$insurerId'
import { Route as AuthenticatedAppEmployeesEmployeeIdRouteImport } from './routes/_authenticated/_app/employees.$employeeId'
import { Route as AuthenticatedAppClientsClientIdRouteImport } from './routes/_authenticated/_app/clients.$clientId'
import { Route as AuthenticatedAppClientAdminsClientAdminIdRouteImport } from './routes/_authenticated/_app/client-admins.$clientAdminId'
import { Route as AuthenticatedAppClaimsClaimIdRouteImport } from './routes/_authenticated/_app/claims.$claimId'
import { Route as AuthenticatedAppAgentsAgentIdRouteImport } from './routes/_authenticated/_app/agents.$agentId'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestResetPasswordRoute = GuestResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => GuestRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const GuestForgotPasswordRoute = GuestForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRoute,
} as any)
const GuestAcceptInvitationRoute = GuestAcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => GuestRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppUsersRoute = AuthenticatedAppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNewClaimRoute =
  AuthenticatedAppNewClaimRouteImport.update({
    id: '/new-claim',
    path: '/new-claim',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInsurersRoute =
  AuthenticatedAppInsurersRouteImport.update({
    id: '/insurers',
    path: '/insurers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClientsRoute = AuthenticatedAppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppClaimsRoute = AuthenticatedAppClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppUsersIndexRoute =
  AuthenticatedAppUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppUsersRoute,
  } as any)
const AuthenticatedAppInsurersIndexRoute =
  AuthenticatedAppInsurersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppInsurersRoute,
  } as any)
const AuthenticatedAppClientsIndexRoute =
  AuthenticatedAppClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppClientsRoute,
  } as any)
const AuthenticatedAppClaimsIndexRoute =
  AuthenticatedAppClaimsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppClaimsRoute,
  } as any)
const AuthenticatedAppInsurersInsurerIdRoute =
  AuthenticatedAppInsurersInsurerIdRouteImport.update({
    id: '/$insurerId',
    path: '/$insurerId',
    getParentRoute: () => AuthenticatedAppInsurersRoute,
  } as any)
const AuthenticatedAppEmployeesEmployeeIdRoute =
  AuthenticatedAppEmployeesEmployeeIdRouteImport.update({
    id: '/employees/$employeeId',
    path: '/employees/$employeeId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClientsClientIdRoute =
  AuthenticatedAppClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedAppClientsRoute,
  } as any)
const AuthenticatedAppClientAdminsClientAdminIdRoute =
  AuthenticatedAppClientAdminsClientAdminIdRouteImport.update({
    id: '/client-admins/$clientAdminId',
    path: '/client-admins/$clientAdminId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClaimsClaimIdRoute =
  AuthenticatedAppClaimsClaimIdRouteImport.update({
    id: '/$claimId',
    path: '/$claimId',
    getParentRoute: () => AuthenticatedAppClaimsRoute,
  } as any)
const AuthenticatedAppAgentsAgentIdRoute =
  AuthenticatedAppAgentsAgentIdRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/brand': typeof BrandRoute
  '/test': typeof TestRoute
  '/accept-invitation': typeof GuestAcceptInvitationRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/claims': typeof AuthenticatedAppClaimsRouteWithChildren
  '/clients': typeof AuthenticatedAppClientsRouteWithChildren
  '/insurers': typeof AuthenticatedAppInsurersRouteWithChildren
  '/new-claim': typeof AuthenticatedAppNewClaimRoute
  '/users': typeof AuthenticatedAppUsersRouteWithChildren
  '/': typeof AuthenticatedAppIndexRoute
  '/agents/$agentId': typeof AuthenticatedAppAgentsAgentIdRoute
  '/claims/$claimId': typeof AuthenticatedAppClaimsClaimIdRoute
  '/client-admins/$clientAdminId': typeof AuthenticatedAppClientAdminsClientAdminIdRoute
  '/clients/$clientId': typeof AuthenticatedAppClientsClientIdRoute
  '/employees/$employeeId': typeof AuthenticatedAppEmployeesEmployeeIdRoute
  '/insurers/$insurerId': typeof AuthenticatedAppInsurersInsurerIdRoute
  '/claims/': typeof AuthenticatedAppClaimsIndexRoute
  '/clients/': typeof AuthenticatedAppClientsIndexRoute
  '/insurers/': typeof AuthenticatedAppInsurersIndexRoute
  '/users/': typeof AuthenticatedAppUsersIndexRoute
}
export interface FileRoutesByTo {
  '/brand': typeof BrandRoute
  '/test': typeof TestRoute
  '/accept-invitation': typeof GuestAcceptInvitationRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/new-claim': typeof AuthenticatedAppNewClaimRoute
  '/': typeof AuthenticatedAppIndexRoute
  '/agents/$agentId': typeof AuthenticatedAppAgentsAgentIdRoute
  '/claims/$claimId': typeof AuthenticatedAppClaimsClaimIdRoute
  '/client-admins/$clientAdminId': typeof AuthenticatedAppClientAdminsClientAdminIdRoute
  '/clients/$clientId': typeof AuthenticatedAppClientsClientIdRoute
  '/employees/$employeeId': typeof AuthenticatedAppEmployeesEmployeeIdRoute
  '/insurers/$insurerId': typeof AuthenticatedAppInsurersInsurerIdRoute
  '/claims': typeof AuthenticatedAppClaimsIndexRoute
  '/clients': typeof AuthenticatedAppClientsIndexRoute
  '/insurers': typeof AuthenticatedAppInsurersIndexRoute
  '/users': typeof AuthenticatedAppUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/brand': typeof BrandRoute
  '/test': typeof TestRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_guest/accept-invitation': typeof GuestAcceptInvitationRoute
  '/_guest/forgot-password': typeof GuestForgotPasswordRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/reset-password': typeof GuestResetPasswordRoute
  '/_authenticated/_app/claims': typeof AuthenticatedAppClaimsRouteWithChildren
  '/_authenticated/_app/clients': typeof AuthenticatedAppClientsRouteWithChildren
  '/_authenticated/_app/insurers': typeof AuthenticatedAppInsurersRouteWithChildren
  '/_authenticated/_app/new-claim': typeof AuthenticatedAppNewClaimRoute
  '/_authenticated/_app/users': typeof AuthenticatedAppUsersRouteWithChildren
  '/_authenticated/_app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/_app/agents/$agentId': typeof AuthenticatedAppAgentsAgentIdRoute
  '/_authenticated/_app/claims/$claimId': typeof AuthenticatedAppClaimsClaimIdRoute
  '/_authenticated/_app/client-admins/$clientAdminId': typeof AuthenticatedAppClientAdminsClientAdminIdRoute
  '/_authenticated/_app/clients/$clientId': typeof AuthenticatedAppClientsClientIdRoute
  '/_authenticated/_app/employees/$employeeId': typeof AuthenticatedAppEmployeesEmployeeIdRoute
  '/_authenticated/_app/insurers/$insurerId': typeof AuthenticatedAppInsurersInsurerIdRoute
  '/_authenticated/_app/claims/': typeof AuthenticatedAppClaimsIndexRoute
  '/_authenticated/_app/clients/': typeof AuthenticatedAppClientsIndexRoute
  '/_authenticated/_app/insurers/': typeof AuthenticatedAppInsurersIndexRoute
  '/_authenticated/_app/users/': typeof AuthenticatedAppUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/brand'
    | '/test'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/claims'
    | '/clients'
    | '/insurers'
    | '/new-claim'
    | '/users'
    | '/'
    | '/agents/$agentId'
    | '/claims/$claimId'
    | '/client-admins/$clientAdminId'
    | '/clients/$clientId'
    | '/employees/$employeeId'
    | '/insurers/$insurerId'
    | '/claims/'
    | '/clients/'
    | '/insurers/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/brand'
    | '/test'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/new-claim'
    | '/'
    | '/agents/$agentId'
    | '/claims/$claimId'
    | '/client-admins/$clientAdminId'
    | '/clients/$clientId'
    | '/employees/$employeeId'
    | '/insurers/$insurerId'
    | '/claims'
    | '/clients'
    | '/insurers'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_guest'
    | '/brand'
    | '/test'
    | '/_authenticated/_app'
    | '/_guest/accept-invitation'
    | '/_guest/forgot-password'
    | '/_guest/login'
    | '/_guest/reset-password'
    | '/_authenticated/_app/claims'
    | '/_authenticated/_app/clients'
    | '/_authenticated/_app/insurers'
    | '/_authenticated/_app/new-claim'
    | '/_authenticated/_app/users'
    | '/_authenticated/_app/'
    | '/_authenticated/_app/agents/$agentId'
    | '/_authenticated/_app/claims/$claimId'
    | '/_authenticated/_app/client-admins/$clientAdminId'
    | '/_authenticated/_app/clients/$clientId'
    | '/_authenticated/_app/employees/$employeeId'
    | '/_authenticated/_app/insurers/$insurerId'
    | '/_authenticated/_app/claims/'
    | '/_authenticated/_app/clients/'
    | '/_authenticated/_app/insurers/'
    | '/_authenticated/_app/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  BrandRoute: typeof BrandRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/reset-password': {
      id: '/_guest/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof GuestResetPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/accept-invitation': {
      id: '/_guest/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof GuestAcceptInvitationRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app/': {
      id: '/_authenticated/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/users': {
      id: '/_authenticated/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedAppUsersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/new-claim': {
      id: '/_authenticated/_app/new-claim'
      path: '/new-claim'
      fullPath: '/new-claim'
      preLoaderRoute: typeof AuthenticatedAppNewClaimRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/insurers': {
      id: '/_authenticated/_app/insurers'
      path: '/insurers'
      fullPath: '/insurers'
      preLoaderRoute: typeof AuthenticatedAppInsurersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/clients': {
      id: '/_authenticated/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedAppClientsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/claims': {
      id: '/_authenticated/_app/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof AuthenticatedAppClaimsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/users/': {
      id: '/_authenticated/_app/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedAppUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAppUsersRoute
    }
    '/_authenticated/_app/insurers/': {
      id: '/_authenticated/_app/insurers/'
      path: '/'
      fullPath: '/insurers/'
      preLoaderRoute: typeof AuthenticatedAppInsurersIndexRouteImport
      parentRoute: typeof AuthenticatedAppInsurersRoute
    }
    '/_authenticated/_app/clients/': {
      id: '/_authenticated/_app/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedAppClientsIndexRouteImport
      parentRoute: typeof AuthenticatedAppClientsRoute
    }
    '/_authenticated/_app/claims/': {
      id: '/_authenticated/_app/claims/'
      path: '/'
      fullPath: '/claims/'
      preLoaderRoute: typeof AuthenticatedAppClaimsIndexRouteImport
      parentRoute: typeof AuthenticatedAppClaimsRoute
    }
    '/_authenticated/_app/insurers/$insurerId': {
      id: '/_authenticated/_app/insurers/$insurerId'
      path: '/$insurerId'
      fullPath: '/insurers/$insurerId'
      preLoaderRoute: typeof AuthenticatedAppInsurersInsurerIdRouteImport
      parentRoute: typeof AuthenticatedAppInsurersRoute
    }
    '/_authenticated/_app/employees/$employeeId': {
      id: '/_authenticated/_app/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof AuthenticatedAppEmployeesEmployeeIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/clients/$clientId': {
      id: '/_authenticated/_app/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedAppClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedAppClientsRoute
    }
    '/_authenticated/_app/client-admins/$clientAdminId': {
      id: '/_authenticated/_app/client-admins/$clientAdminId'
      path: '/client-admins/$clientAdminId'
      fullPath: '/client-admins/$clientAdminId'
      preLoaderRoute: typeof AuthenticatedAppClientAdminsClientAdminIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/claims/$claimId': {
      id: '/_authenticated/_app/claims/$claimId'
      path: '/$claimId'
      fullPath: '/claims/$claimId'
      preLoaderRoute: typeof AuthenticatedAppClaimsClaimIdRouteImport
      parentRoute: typeof AuthenticatedAppClaimsRoute
    }
    '/_authenticated/_app/agents/$agentId': {
      id: '/_authenticated/_app/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAppAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppClaimsRouteChildren {
  AuthenticatedAppClaimsClaimIdRoute: typeof AuthenticatedAppClaimsClaimIdRoute
  AuthenticatedAppClaimsIndexRoute: typeof AuthenticatedAppClaimsIndexRoute
}

const AuthenticatedAppClaimsRouteChildren: AuthenticatedAppClaimsRouteChildren =
  {
    AuthenticatedAppClaimsClaimIdRoute: AuthenticatedAppClaimsClaimIdRoute,
    AuthenticatedAppClaimsIndexRoute: AuthenticatedAppClaimsIndexRoute,
  }

const AuthenticatedAppClaimsRouteWithChildren =
  AuthenticatedAppClaimsRoute._addFileChildren(
    AuthenticatedAppClaimsRouteChildren,
  )

interface AuthenticatedAppClientsRouteChildren {
  AuthenticatedAppClientsClientIdRoute: typeof AuthenticatedAppClientsClientIdRoute
  AuthenticatedAppClientsIndexRoute: typeof AuthenticatedAppClientsIndexRoute
}

const AuthenticatedAppClientsRouteChildren: AuthenticatedAppClientsRouteChildren =
  {
    AuthenticatedAppClientsClientIdRoute: AuthenticatedAppClientsClientIdRoute,
    AuthenticatedAppClientsIndexRoute: AuthenticatedAppClientsIndexRoute,
  }

const AuthenticatedAppClientsRouteWithChildren =
  AuthenticatedAppClientsRoute._addFileChildren(
    AuthenticatedAppClientsRouteChildren,
  )

interface AuthenticatedAppInsurersRouteChildren {
  AuthenticatedAppInsurersInsurerIdRoute: typeof AuthenticatedAppInsurersInsurerIdRoute
  AuthenticatedAppInsurersIndexRoute: typeof AuthenticatedAppInsurersIndexRoute
}

const AuthenticatedAppInsurersRouteChildren: AuthenticatedAppInsurersRouteChildren =
  {
    AuthenticatedAppInsurersInsurerIdRoute:
      AuthenticatedAppInsurersInsurerIdRoute,
    AuthenticatedAppInsurersIndexRoute: AuthenticatedAppInsurersIndexRoute,
  }

const AuthenticatedAppInsurersRouteWithChildren =
  AuthenticatedAppInsurersRoute._addFileChildren(
    AuthenticatedAppInsurersRouteChildren,
  )

interface AuthenticatedAppUsersRouteChildren {
  AuthenticatedAppUsersIndexRoute: typeof AuthenticatedAppUsersIndexRoute
}

const AuthenticatedAppUsersRouteChildren: AuthenticatedAppUsersRouteChildren = {
  AuthenticatedAppUsersIndexRoute: AuthenticatedAppUsersIndexRoute,
}

const AuthenticatedAppUsersRouteWithChildren =
  AuthenticatedAppUsersRoute._addFileChildren(
    AuthenticatedAppUsersRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppClaimsRoute: typeof AuthenticatedAppClaimsRouteWithChildren
  AuthenticatedAppClientsRoute: typeof AuthenticatedAppClientsRouteWithChildren
  AuthenticatedAppInsurersRoute: typeof AuthenticatedAppInsurersRouteWithChildren
  AuthenticatedAppNewClaimRoute: typeof AuthenticatedAppNewClaimRoute
  AuthenticatedAppUsersRoute: typeof AuthenticatedAppUsersRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAgentsAgentIdRoute: typeof AuthenticatedAppAgentsAgentIdRoute
  AuthenticatedAppClientAdminsClientAdminIdRoute: typeof AuthenticatedAppClientAdminsClientAdminIdRoute
  AuthenticatedAppEmployeesEmployeeIdRoute: typeof AuthenticatedAppEmployeesEmployeeIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppClaimsRoute: AuthenticatedAppClaimsRouteWithChildren,
  AuthenticatedAppClientsRoute: AuthenticatedAppClientsRouteWithChildren,
  AuthenticatedAppInsurersRoute: AuthenticatedAppInsurersRouteWithChildren,
  AuthenticatedAppNewClaimRoute: AuthenticatedAppNewClaimRoute,
  AuthenticatedAppUsersRoute: AuthenticatedAppUsersRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAgentsAgentIdRoute: AuthenticatedAppAgentsAgentIdRoute,
  AuthenticatedAppClientAdminsClientAdminIdRoute:
    AuthenticatedAppClientAdminsClientAdminIdRoute,
  AuthenticatedAppEmployeesEmployeeIdRoute:
    AuthenticatedAppEmployeesEmployeeIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GuestRouteChildren {
  GuestAcceptInvitationRoute: typeof GuestAcceptInvitationRoute
  GuestForgotPasswordRoute: typeof GuestForgotPasswordRoute
  GuestLoginRoute: typeof GuestLoginRoute
  GuestResetPasswordRoute: typeof GuestResetPasswordRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestAcceptInvitationRoute: GuestAcceptInvitationRoute,
  GuestForgotPasswordRoute: GuestForgotPasswordRoute,
  GuestLoginRoute: GuestLoginRoute,
  GuestResetPasswordRoute: GuestResetPasswordRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  BrandRoute: BrandRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
